# friction_data.py

# (bolt_material, mating_material, lubrication) → K value

friction_table = {
    # Steel
    ("Steel", "Steel", "Dry"): 0.16,
    ("Steel", "Steel", "Oiled"): 0.12,
    ("Steel", "Steel", "Waxed"): 0.10,
    ("Steel", "Steel", "Threadlock"): 0.15,
    ("Steel", "Stainless", "Dry"): 0.18,
    ("Steel", "Stainless", "Oiled"): 0.14,
    ("Steel", "Stainless", "Waxed"): 0.11,
    ("Steel", "Stainless", "Threadlock"): 0.16,
    ("Steel", "Aluminum", "Dry"): 0.22,
    ("Steel", "Aluminum", "Oiled"): 0.16,
    ("Steel", "Aluminum", "Waxed"): 0.12,
    ("Steel", "Aluminum", "Threadlock"): 0.19,
    ("Steel", "Copper", "Dry"): 0.23,
    ("Steel", "Copper", "Oiled"): 0.17,
    ("Steel", "Copper", "Waxed"): 0.12,
    ("Steel", "Copper", "Threadlock"): 0.19,
    ("Steel", "Brass", "Dry"): 0.21,
    ("Steel", "Brass", "Oiled"): 0.16,
    ("Steel", "Brass", "Waxed"): 0.12,
    ("Steel", "Brass", "Threadlock"): 0.18,
    ("Steel", "Titanium", "Dry"): 0.22,
    ("Steel", "Titanium", "Oiled"): 0.17,
    ("Steel", "Titanium", "Waxed"): 0.13,
    ("Steel", "Titanium", "Threadlock"): 0.18,

    # Stainless
    ("Stainless", "Steel", "Dry"): 0.20,
    ("Stainless", "Steel", "Oiled"): 0.15,
    ("Stainless", "Steel", "Waxed"): 0.12,
    ("Stainless", "Steel", "Threadlock"): 0.18,
    ("Stainless", "Stainless", "Dry"): 0.22,
    ("Stainless", "Stainless", "Oiled"): 0.15,
    ("Stainless", "Stainless", "Waxed"): 0.13,
    ("Stainless", "Stainless", "Threadlock"): 0.20,
    ("Stainless", "Aluminum", "Dry"): 0.26,
    ("Stainless", "Aluminum", "Oiled"): 0.19,
    ("Stainless", "Aluminum", "Waxed"): 0.15,
    ("Stainless", "Aluminum", "Threadlock"): 0.21,
    ("Stainless", "Copper", "Dry"): 0.24,
    ("Stainless", "Copper", "Oiled"): 0.18,
    ("Stainless", "Copper", "Waxed"): 0.14,
    ("Stainless", "Copper", "Threadlock"): 0.21,
    ("Stainless", "Brass", "Dry"): 0.22,
    ("Stainless", "Brass", "Oiled"): 0.17,
    ("Stainless", "Brass", "Waxed"): 0.13,
    ("Stainless", "Brass", "Threadlock"): 0.19,
    ("Stainless", "Titanium", "Dry"): 0.24,
    ("Stainless", "Titanium", "Oiled"): 0.18,
    ("Stainless", "Titanium", "Waxed"): 0.15,
    ("Stainless", "Titanium", "Threadlock"): 0.21,

    # Aluminum
    ("Aluminum", "Steel", "Dry"): 0.24,
    ("Aluminum", "Steel", "Oiled"): 0.16,
    ("Aluminum", "Steel", "Waxed"): 0.13,
    ("Aluminum", "Steel", "Threadlock"): 0.20,
    ("Aluminum", "Aluminum", "Dry"): 0.30,
    ("Aluminum", "Aluminum", "Oiled"): 0.18,
    ("Aluminum", "Aluminum", "Waxed"): 0.14,
    ("Aluminum", "Aluminum", "Threadlock"): 0.23,
    ("Aluminum", "Stainless", "Dry"): 0.27,
    ("Aluminum", "Stainless", "Oiled"): 0.20,
    ("Aluminum", "Stainless", "Waxed"): 0.15,
    ("Aluminum", "Stainless", "Threadlock"): 0.23,
    ("Aluminum", "Copper", "Dry"): 0.26,
    ("Aluminum", "Copper", "Oiled"): 0.20,
    ("Aluminum", "Copper", "Waxed"): 0.15,
    ("Aluminum", "Copper", "Threadlock"): 0.22,
    ("Aluminum", "Brass", "Dry"): 0.25,
    ("Aluminum", "Brass", "Oiled"): 0.19,
    ("Aluminum", "Brass", "Waxed"): 0.15,
    ("Aluminum", "Brass", "Threadlock"): 0.22,
    ("Aluminum", "Titanium", "Dry"): 0.28,
    ("Aluminum", "Titanium", "Oiled"): 0.22,
    ("Aluminum", "Titanium", "Waxed"): 0.17,
    ("Aluminum", "Titanium", "Threadlock"): 0.24,

    # Brass
    ("Brass", "Steel", "Dry"): 0.20,
    ("Brass", "Steel", "Oiled"): 0.15,
    ("Brass", "Steel", "Waxed"): 0.13,
    ("Brass", "Steel", "Threadlock"): 0.18,
    ("Brass", "Brass", "Dry"): 0.21,
    ("Brass", "Brass", "Oiled"): 0.16,
    ("Brass", "Brass", "Waxed"): 0.13,
    ("Brass", "Brass", "Threadlock"): 0.19,
    ("Brass", "Aluminum", "Dry"): 0.24,
    ("Brass", "Aluminum", "Oiled"): 0.18,
    ("Brass", "Aluminum", "Waxed"): 0.15,
    ("Brass", "Aluminum", "Threadlock"): 0.22,
    ("Brass", "Stainless", "Dry"): 0.22,
    ("Brass", "Stainless", "Oiled"): 0.16,
    ("Brass", "Stainless", "Waxed"): 0.13,
    ("Brass", "Stainless", "Threadlock"): 0.19,
    ("Brass", "Copper", "Dry"): 0.22,
    ("Brass", "Copper", "Oiled"): 0.16,
    ("Brass", "Copper", "Waxed"): 0.13,
    ("Brass", "Copper", "Threadlock"): 0.19,
    ("Brass", "Titanium", "Dry"): 0.23,
    ("Brass", "Titanium", "Oiled"): 0.18,
    ("Brass", "Titanium", "Waxed"): 0.15,
    ("Brass", "Titanium", "Threadlock"): 0.21,

    # Copper
    ("Copper", "Steel", "Dry"): 0.21,
    ("Copper", "Steel", "Oiled"): 0.16,
    ("Copper", "Steel", "Waxed"): 0.13,
    ("Copper", "Steel", "Threadlock"): 0.18,
    ("Copper", "Copper", "Dry"): 0.23,
    ("Copper", "Copper", "Oiled"): 0.16,
    ("Copper", "Copper", "Waxed"): 0.13,
    ("Copper", "Copper", "Threadlock"): 0.19,
    ("Copper", "Aluminum", "Dry"): 0.24,
    ("Copper", "Aluminum", "Oiled"): 0.18,
    ("Copper", "Aluminum", "Waxed"): 0.15,
    ("Copper", "Aluminum", "Threadlock"): 0.22,
    ("Copper", "Stainless", "Dry"): 0.22,
    ("Copper", "Stainless", "Oiled"): 0.17,
    ("Copper", "Stainless", "Waxed"): 0.14,
    ("Copper", "Stainless", "Threadlock"): 0.20,
    ("Copper", "Brass", "Dry"): 0.22,
    ("Copper", "Brass", "Oiled"): 0.17,
    ("Copper", "Brass", "Waxed"): 0.14,
    ("Copper", "Brass", "Threadlock"): 0.20,
    ("Copper", "Titanium", "Dry"): 0.24,
    ("Copper", "Titanium", "Oiled"): 0.19,
    ("Copper", "Titanium", "Waxed"): 0.16,
    ("Copper", "Titanium", "Threadlock"): 0.21,

    # Titanium
    ("Titanium", "Steel", "Dry"): 0.22,
    ("Titanium", "Steel", "Oiled"): 0.17,
    ("Titanium", "Steel", "Waxed"): 0.14,
    ("Titanium", "Steel", "Threadlock"): 0.19,
    ("Titanium", "Titanium", "Dry"): 0.26,
    ("Titanium", "Titanium", "Oiled"): 0.19,
    ("Titanium", "Titanium", "Waxed"): 0.16,
    ("Titanium", "Titanium", "Threadlock"): 0.22,
    ("Titanium", "Aluminum", "Dry"): 0.28,
    ("Titanium", "Aluminum", "Oiled"): 0.21,
    ("Titanium", "Aluminum", "Waxed"): 0.17,
    ("Titanium", "Aluminum", "Threadlock"): 0.23,
    ("Titanium", "Stainless", "Dry"): 0.24,
    ("Titanium", "Stainless", "Oiled"): 0.19,
    ("Titanium", "Stainless", "Waxed"): 0.16,
    ("Titanium", "Stainless", "Threadlock"): 0.22,
    ("Titanium", "Brass", "Dry"): 0.22,
    ("Titanium", "Brass", "Oiled"): 0.18,
    ("Titanium", "Brass", "Waxed"): 0.15,
    ("Titanium", "Brass", "Threadlock"): 0.21,
    ("Titanium", "Copper", "Dry"): 0.23,
    ("Titanium", "Copper", "Oiled"): 0.18,
    ("Titanium", "Copper", "Waxed"): 0.15,
    ("Titanium", "Copper", "Threadlock"): 0.21,
}
